spring.application.name=UrbanNest
spring.datasource.url=jdbc:postgresql://localhost:5432/urbannest_db
spring.datasource.username=postgres
spring.datasource.password=Jaya2001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true